name: redis-gui
version: '1.2.7'
summary: 'Graphical UI for managing Redis databases'
description: |
  Manage your Redis database with graphical UI.

  **Main features**

  * SSH tunneling
  * Namespacing support
  * JSON viewer
  * Console with command args and summary
  * Light and dark mode
  * TTL management

  https://github.com/ekvedaras/redis-gui

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    plugin: nil
